// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v7.35.0
// source: proto/server.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CANFrameTypeEnum int32

const (
	CANFrameTypeEnum_Incoming                 CANFrameTypeEnum = 0
	CANFrameTypeEnum_Outgoing                 CANFrameTypeEnum = 1
	CANFrameTypeEnum_OutgoingResponseRequired CANFrameTypeEnum = 2
)

// Enum value maps for CANFrameTypeEnum.
var (
	CANFrameTypeEnum_name = map[int32]string{
		0: "Incoming",
		1: "Outgoing",
		2: "OutgoingResponseRequired",
	}
	CANFrameTypeEnum_value = map[string]int32{
		"Incoming":                 0,
		"Outgoing":                 1,
		"OutgoingResponseRequired": 2,
	}
)

func (x CANFrameTypeEnum) Enum() *CANFrameTypeEnum {
	p := new(CANFrameTypeEnum)
	*p = x
	return p
}

func (x CANFrameTypeEnum) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (CANFrameTypeEnum) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_server_proto_enumTypes[0].Descriptor()
}

func (CANFrameTypeEnum) Type() protoreflect.EnumType {
	return &file_proto_server_proto_enumTypes[0]
}

func (x CANFrameTypeEnum) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use CANFrameTypeEnum.Descriptor instead.
func (CANFrameTypeEnum) EnumDescriptor() ([]byte, []int) {
	return file_proto_server_proto_rawDescGZIP(), []int{0}
}

// EventLevel mirrors gocan.EventType so adapter event severity survives the wire
// instead of being collapsed to a single "info" system message.
type EventLevel int32

const (
	EventLevel_EVENT_DEBUG EventLevel = 0
	EventLevel_EVENT_INFO  EventLevel = 1
	EventLevel_EVENT_WARN  EventLevel = 2
	EventLevel_EVENT_ERROR EventLevel = 3
	EventLevel_EVENT_FATAL EventLevel = 4
)

// Enum value maps for EventLevel.
var (
	EventLevel_name = map[int32]string{
		0: "EVENT_DEBUG",
		1: "EVENT_INFO",
		2: "EVENT_WARN",
		3: "EVENT_ERROR",
		4: "EVENT_FATAL",
	}
	EventLevel_value = map[string]int32{
		"EVENT_DEBUG": 0,
		"EVENT_INFO":  1,
		"EVENT_WARN":  2,
		"EVENT_ERROR": 3,
		"EVENT_FATAL": 4,
	}
)

func (x EventLevel) Enum() *EventLevel {
	p := new(EventLevel)
	*p = x
	return p
}

func (x EventLevel) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (EventLevel) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_server_proto_enumTypes[1].Descriptor()
}

func (EventLevel) Type() protoreflect.EnumType {
	return &file_proto_server_proto_enumTypes[1]
}

func (x EventLevel) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use EventLevel.Descriptor instead.
func (EventLevel) EnumDescriptor() ([]byte, []int) {
	return file_proto_server_proto_rawDescGZIP(), []int{1}
}

type Adapters struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Adapters      []*AdapterInfo         `protobuf:"bytes,1,rep,name=adapters,proto3" json:"adapters,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Adapters) Reset() {
	*x = Adapters{}
	mi := &file_proto_server_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Adapters) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Adapters) ProtoMessage() {}

func (x *Adapters) ProtoReflect() protoreflect.Message {
	mi := &file_proto_server_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Adapters.ProtoReflect.Descriptor instead.
func (*Adapters) Descriptor() ([]byte, []int) {
	return file_proto_server_proto_rawDescGZIP(), []int{0}
}

func (x *Adapters) GetAdapters() []*AdapterInfo {
	if x != nil {
		return x.Adapters
	}
	return nil
}

type AdapterInfo struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Name              string                 `protobuf:"bytes,1,opt,name=Name,proto3" json:"Name,omitempty"`
	Description       string                 `protobuf:"bytes,2,opt,name=Description,proto3" json:"Description,omitempty"`
	Capabilities      *AdapterCapabilities   `protobuf:"bytes,3,opt,name=Capabilities,proto3" json:"Capabilities,omitempty"`
	RequireSerialPort bool                   `protobuf:"varint,4,opt,name=RequireSerialPort,proto3" json:"RequireSerialPort,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *AdapterInfo) Reset() {
	*x = AdapterInfo{}
	mi := &file_proto_server_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AdapterInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AdapterInfo) ProtoMessage() {}

func (x *AdapterInfo) ProtoReflect() protoreflect.Message {
	mi := &file_proto_server_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AdapterInfo.ProtoReflect.Descriptor instead.
func (*AdapterInfo) Descriptor() ([]byte, []int) {
	return file_proto_server_proto_rawDescGZIP(), []int{1}
}

func (x *AdapterInfo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *AdapterInfo) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *AdapterInfo) GetCapabilities() *AdapterCapabilities {
	if x != nil {
		return x.Capabilities
	}
	return nil
}

func (x *AdapterInfo) GetRequireSerialPort() bool {
	if x != nil {
		return x.RequireSerialPort
	}
	return false
}

type SerialPorts struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ports         []*SerialPort          `protobuf:"bytes,1,rep,name=ports,proto3" json:"ports,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SerialPorts) Reset() {
	*x = SerialPorts{}
	mi := &file_proto_server_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SerialPorts) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SerialPorts) ProtoMessage() {}

func (x *SerialPorts) ProtoReflect() protoreflect.Message {
	mi := &file_proto_server_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SerialPorts.ProtoReflect.Descriptor instead.
func (*SerialPorts) Descriptor() ([]byte, []int) {
	return file_proto_server_proto_rawDescGZIP(), []int{2}
}

func (x *SerialPorts) GetPorts() []*SerialPort {
	if x != nil {
		return x.Ports
	}
	return nil
}

type SerialPort struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=Name,proto3" json:"Name,omitempty"`
	Description   string                 `protobuf:"bytes,2,opt,name=Description,proto3" json:"Description,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SerialPort) Reset() {
	*x = SerialPort{}
	mi := &file_proto_server_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SerialPort) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SerialPort) ProtoMessage() {}

func (x *SerialPort) ProtoReflect() protoreflect.Message {
	mi := &file_proto_server_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SerialPort.ProtoReflect.Descriptor instead.
func (*SerialPort) Descriptor() ([]byte, []int) {
	return file_proto_server_proto_rawDescGZIP(), []int{3}
}

func (x *SerialPort) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *SerialPort) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

type AdapterCapabilities struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	HSCAN         bool                   `protobuf:"varint,1,opt,name=HSCAN,proto3" json:"HSCAN,omitempty"`
	SWCAN         bool                   `protobuf:"varint,2,opt,name=SWCAN,proto3" json:"SWCAN,omitempty"`
	KLine         bool                   `protobuf:"varint,3,opt,name=KLine,proto3" json:"KLine,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AdapterCapabilities) Reset() {
	*x = AdapterCapabilities{}
	mi := &file_proto_server_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AdapterCapabilities) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AdapterCapabilities) ProtoMessage() {}

func (x *AdapterCapabilities) ProtoReflect() protoreflect.Message {
	mi := &file_proto_server_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AdapterCapabilities.ProtoReflect.Descriptor instead.
func (*AdapterCapabilities) Descriptor() ([]byte, []int) {
	return file_proto_server_proto_rawDescGZIP(), []int{4}
}

func (x *AdapterCapabilities) GetHSCAN() bool {
	if x != nil {
		return x.HSCAN
	}
	return false
}

func (x *AdapterCapabilities) GetSWCAN() bool {
	if x != nil {
		return x.SWCAN
	}
	return false
}

func (x *AdapterCapabilities) GetKLine() bool {
	if x != nil {
		return x.KLine
	}
	return false
}

type Command struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          []byte                 `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Command) Reset() {
	*x = Command{}
	mi := &file_proto_server_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Command) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Command) ProtoMessage() {}

func (x *Command) ProtoReflect() protoreflect.Message {
	mi := &file_proto_server_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Command.ProtoReflect.Descriptor instead.
func (*Command) Descriptor() ([]byte, []int) {
	return file_proto_server_proto_rawDescGZIP(), []int{5}
}

func (x *Command) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

type CommandResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          []byte                 `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CommandResponse) Reset() {
	*x = CommandResponse{}
	mi := &file_proto_server_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CommandResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommandResponse) ProtoMessage() {}

func (x *CommandResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_server_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommandResponse.ProtoReflect.Descriptor instead.
func (*CommandResponse) Descriptor() ([]byte, []int) {
	return file_proto_server_proto_rawDescGZIP(), []int{6}
}

func (x *CommandResponse) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

// CANFrame is the flat representation of a single CAN frame. Frame-type and
// response-count are inlined (previously a nested CANFrameType message) so the
// hot streaming path allocates a single message with scalar (value) fields.
type CANFrame struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint32                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Data          []byte                 `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	FrameType     CANFrameTypeEnum       `protobuf:"varint,3,opt,name=frame_type,json=frameType,proto3,enum=CANFrameTypeEnum" json:"frame_type,omitempty"`
	Responses     uint32                 `protobuf:"varint,4,opt,name=responses,proto3" json:"responses,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CANFrame) Reset() {
	*x = CANFrame{}
	mi := &file_proto_server_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CANFrame) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CANFrame) ProtoMessage() {}

func (x *CANFrame) ProtoReflect() protoreflect.Message {
	mi := &file_proto_server_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CANFrame.ProtoReflect.Descriptor instead.
func (*CANFrame) Descriptor() ([]byte, []int) {
	return file_proto_server_proto_rawDescGZIP(), []int{7}
}

func (x *CANFrame) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *CANFrame) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *CANFrame) GetFrameType() CANFrameTypeEnum {
	if x != nil {
		return x.FrameType
	}
	return CANFrameTypeEnum_Incoming
}

func (x *CANFrame) GetResponses() uint32 {
	if x != nil {
		return x.Responses
	}
	return 0
}

type Event struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Level         EventLevel             `protobuf:"varint,1,opt,name=level,proto3,enum=EventLevel" json:"level,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Event) Reset() {
	*x = Event{}
	mi := &file_proto_server_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Event) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Event) ProtoMessage() {}

func (x *Event) ProtoReflect() protoreflect.Message {
	mi := &file_proto_server_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Event.ProtoReflect.Descriptor instead.
func (*Event) Descriptor() ([]byte, []int) {
	return file_proto_server_proto_rawDescGZIP(), []int{8}
}

func (x *Event) GetLevel() EventLevel {
	if x != nil {
		return x.Level
	}
	return EventLevel_EVENT_DEBUG
}

func (x *Event) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// StreamMessage is what the gateway sends to the client: either a CAN frame or a
// typed event/error. The client→gateway direction stays a plain CANFrame.
type StreamMessage struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Payload:
	//
	//	*StreamMessage_Frame
	//	*StreamMessage_Event
	Payload       isStreamMessage_Payload `protobuf_oneof:"payload"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StreamMessage) Reset() {
	*x = StreamMessage{}
	mi := &file_proto_server_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamMessage) ProtoMessage() {}

func (x *StreamMessage) ProtoReflect() protoreflect.Message {
	mi := &file_proto_server_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamMessage.ProtoReflect.Descriptor instead.
func (*StreamMessage) Descriptor() ([]byte, []int) {
	return file_proto_server_proto_rawDescGZIP(), []int{9}
}

func (x *StreamMessage) GetPayload() isStreamMessage_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *StreamMessage) GetFrame() *CANFrame {
	if x != nil {
		if x, ok := x.Payload.(*StreamMessage_Frame); ok {
			return x.Frame
		}
	}
	return nil
}

func (x *StreamMessage) GetEvent() *Event {
	if x != nil {
		if x, ok := x.Payload.(*StreamMessage_Event); ok {
			return x.Event
		}
	}
	return nil
}

type isStreamMessage_Payload interface {
	isStreamMessage_Payload()
}

type StreamMessage_Frame struct {
	Frame *CANFrame `protobuf:"bytes,1,opt,name=frame,proto3,oneof"`
}

type StreamMessage_Event struct {
	Event *Event `protobuf:"bytes,2,opt,name=event,proto3,oneof"`
}

func (*StreamMessage_Frame) isStreamMessage_Payload() {}

func (*StreamMessage_Event) isStreamMessage_Payload() {}

var File_proto_server_proto protoreflect.FileDescriptor

const file_proto_server_proto_rawDesc = "" +
	"\n" +
	"\x12proto/server.proto\x1a\x1bgoogle/protobuf/empty.proto\"4\n" +
	"\bAdapters\x12(\n" +
	"\badapters\x18\x01 \x03(\v2\f.AdapterInfoR\badapters\"\xab\x01\n" +
	"\vAdapterInfo\x12\x12\n" +
	"\x04Name\x18\x01 \x01(\tR\x04Name\x12 \n" +
	"\vDescription\x18\x02 \x01(\tR\vDescription\x128\n" +
	"\fCapabilities\x18\x03 \x01(\v2\x14.AdapterCapabilitiesR\fCapabilities\x12,\n" +
	"\x11RequireSerialPort\x18\x04 \x01(\bR\x11RequireSerialPort\"0\n" +
	"\vSerialPorts\x12!\n" +
	"\x05ports\x18\x01 \x03(\v2\v.SerialPortR\x05ports\"B\n" +
	"\n" +
	"SerialPort\x12\x12\n" +
	"\x04Name\x18\x01 \x01(\tR\x04Name\x12 \n" +
	"\vDescription\x18\x02 \x01(\tR\vDescription\"W\n" +
	"\x13AdapterCapabilities\x12\x14\n" +
	"\x05HSCAN\x18\x01 \x01(\bR\x05HSCAN\x12\x14\n" +
	"\x05SWCAN\x18\x02 \x01(\bR\x05SWCAN\x12\x14\n" +
	"\x05KLine\x18\x03 \x01(\bR\x05KLine\"\x1d\n" +
	"\aCommand\x12\x12\n" +
	"\x04data\x18\x01 \x01(\fR\x04data\"%\n" +
	"\x0fCommandResponse\x12\x12\n" +
	"\x04data\x18\x01 \x01(\fR\x04data\"~\n" +
	"\bCANFrame\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\rR\x02id\x12\x12\n" +
	"\x04data\x18\x02 \x01(\fR\x04data\x120\n" +
	"\n" +
	"frame_type\x18\x03 \x01(\x0e2\x11.CANFrameTypeEnumR\tframeType\x12\x1c\n" +
	"\tresponses\x18\x04 \x01(\rR\tresponses\"D\n" +
	"\x05Event\x12!\n" +
	"\x05level\x18\x01 \x01(\x0e2\v.EventLevelR\x05level\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"]\n" +
	"\rStreamMessage\x12!\n" +
	"\x05frame\x18\x01 \x01(\v2\t.CANFrameH\x00R\x05frame\x12\x1e\n" +
	"\x05event\x18\x02 \x01(\v2\x06.EventH\x00R\x05eventB\t\n" +
	"\apayload*L\n" +
	"\x10CANFrameTypeEnum\x12\f\n" +
	"\bIncoming\x10\x00\x12\f\n" +
	"\bOutgoing\x10\x01\x12\x1c\n" +
	"\x18OutgoingResponseRequired\x10\x02*_\n" +
	"\n" +
	"EventLevel\x12\x0f\n" +
	"\vEVENT_DEBUG\x10\x00\x12\x0e\n" +
	"\n" +
	"EVENT_INFO\x10\x01\x12\x0e\n" +
	"\n" +
	"EVENT_WARN\x10\x02\x12\x0f\n" +
	"\vEVENT_ERROR\x10\x03\x12\x0f\n" +
	"\vEVENT_FATAL\x10\x042\xcd\x01\n" +
	"\x05Gocan\x12+\n" +
	"\vSendCommand\x12\b.Command\x1a\x10.CommandResponse\"\x00\x128\n" +
	"\x0eGetSerialPorts\x12\x16.google.protobuf.Empty\x1a\f.SerialPorts\"\x00\x122\n" +
	"\vGetAdapters\x12\x16.google.protobuf.Empty\x1a\t.Adapters\"\x00\x12)\n" +
	"\x06Stream\x12\t.CANFrame\x1a\x0e.StreamMessage\"\x00(\x010\x01B\x1eZ\x1cgithub.com/roffe/gocan/protob\x06proto3"

var (
	file_proto_server_proto_rawDescOnce sync.Once
	file_proto_server_proto_rawDescData []byte
)

func file_proto_server_proto_rawDescGZIP() []byte {
	file_proto_server_proto_rawDescOnce.Do(func() {
		file_proto_server_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_server_proto_rawDesc), len(file_proto_server_proto_rawDesc)))
	})
	return file_proto_server_proto_rawDescData
}

var file_proto_server_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_proto_server_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_proto_server_proto_goTypes = []any{
	(CANFrameTypeEnum)(0),       // 0: CANFrameTypeEnum
	(EventLevel)(0),             // 1: EventLevel
	(*Adapters)(nil),            // 2: Adapters
	(*AdapterInfo)(nil),         // 3: AdapterInfo
	(*SerialPorts)(nil),         // 4: SerialPorts
	(*SerialPort)(nil),          // 5: SerialPort
	(*AdapterCapabilities)(nil), // 6: AdapterCapabilities
	(*Command)(nil),             // 7: Command
	(*CommandResponse)(nil),     // 8: CommandResponse
	(*CANFrame)(nil),            // 9: CANFrame
	(*Event)(nil),               // 10: Event
	(*StreamMessage)(nil),       // 11: StreamMessage
	(*emptypb.Empty)(nil),       // 12: google.protobuf.Empty
}
var file_proto_server_proto_depIdxs = []int32{
	3,  // 0: Adapters.adapters:type_name -> AdapterInfo
	6,  // 1: AdapterInfo.Capabilities:type_name -> AdapterCapabilities
	5,  // 2: SerialPorts.ports:type_name -> SerialPort
	0,  // 3: CANFrame.frame_type:type_name -> CANFrameTypeEnum
	1,  // 4: Event.level:type_name -> EventLevel
	9,  // 5: StreamMessage.frame:type_name -> CANFrame
	10, // 6: StreamMessage.event:type_name -> Event
	7,  // 7: Gocan.SendCommand:input_type -> Command
	12, // 8: Gocan.GetSerialPorts:input_type -> google.protobuf.Empty
	12, // 9: Gocan.GetAdapters:input_type -> google.protobuf.Empty
	9,  // 10: Gocan.Stream:input_type -> CANFrame
	8,  // 11: Gocan.SendCommand:output_type -> CommandResponse
	4,  // 12: Gocan.GetSerialPorts:output_type -> SerialPorts
	2,  // 13: Gocan.GetAdapters:output_type -> Adapters
	11, // 14: Gocan.Stream:output_type -> StreamMessage
	11, // [11:15] is the sub-list for method output_type
	7,  // [7:11] is the sub-list for method input_type
	7,  // [7:7] is the sub-list for extension type_name
	7,  // [7:7] is the sub-list for extension extendee
	0,  // [0:7] is the sub-list for field type_name
}

func init() { file_proto_server_proto_init() }
func file_proto_server_proto_init() {
	if File_proto_server_proto != nil {
		return
	}
	file_proto_server_proto_msgTypes[9].OneofWrappers = []any{
		(*StreamMessage_Frame)(nil),
		(*StreamMessage_Event)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_server_proto_rawDesc), len(file_proto_server_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_server_proto_goTypes,
		DependencyIndexes: file_proto_server_proto_depIdxs,
		EnumInfos:         file_proto_server_proto_enumTypes,
		MessageInfos:      file_proto_server_proto_msgTypes,
	}.Build()
	File_proto_server_proto = out.File
	file_proto_server_proto_goTypes = nil
	file_proto_server_proto_depIdxs = nil
}
